server:
  port: ${port:8083}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/day05?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    password: root
    username: root
  application:
    name: eureka-client-provider
test: ppppppppp
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
      
